title = "Miguel Vila's Blog"
baseURL = 'https://miguelovila.com/'
languageCode = 'en-us'
theme = "hugo-blog-awesome"

# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable  Google Analytics, simply leave the field empty or remove the next line
googleAnalytics = 'G-H4F2DBNDB6' # G-MEASUREMENT_ID

# Enable emojis globally
enableEmoji = true

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]] 
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30

[params]
  sitename = "Miguel Vila's Blog"
  defaultColor = "dark" # set default color mode: dark or light
  custom_css = ["css/mycss.css"] # add custom css files
  description = "Computer and Informatics Engineering student at UA with a passion for Linux, Open Source and Trail Running."

[params.author]
  avatar = "avatar.png" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Miguel Vila's Blog"
  name = "Miguel Vila"
  description = "Computer and Informatics Engineering student at UA with a passion for Linux, Open Source and Trail Running."

[[params.socialIcons]]
name = "github"
url = "https://github.com/miguelovila"

[[params.socialIcons]]
name = "email"
url = "mailto:miguelovila@ua.pt"

[[params.socialIcons]]
name = "mastodon"
url = "https://masto.pt/@miguelovila"