# syntax=docker/dockerfile:1.7

ARG BUN_VERSION=1.3.14

FROM oven/bun:${BUN_VERSION}-alpine AS deps
WORKDIR /app

ENV HUSKY=0

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

FROM deps AS build
WORKDIR /app

ARG FEATURE_FLAGS=all
ARG FEATURE_BLOG
ARG FEATURE_PROJECTS
ARG FEATURE_ABOUT
ARG FEATURE_SEARCH
ARG FEATURE_FLAG_BLOG
ARG FEATURE_FLAG_PROJECTS
ARG FEATURE_FLAG_ABOUT
ARG FEATURE_FLAG_SEARCH
ARG PUBLIC_FEATURE_FLAGS
ARG PUBLIC_FEATURE_BLOG
ARG PUBLIC_FEATURE_PROJECTS
ARG PUBLIC_FEATURE_ABOUT
ARG PUBLIC_FEATURE_SEARCH
ARG PUBLIC_FEATURE_FLAG_BLOG
ARG PUBLIC_FEATURE_FLAG_PROJECTS
ARG PUBLIC_FEATURE_FLAG_ABOUT
ARG PUBLIC_FEATURE_FLAG_SEARCH

ENV ASTRO_TELEMETRY_DISABLED=1 \
    NODE_ENV=production \
    FEATURE_FLAGS=${FEATURE_FLAGS} \
    FEATURE_BLOG=${FEATURE_BLOG} \
    FEATURE_PROJECTS=${FEATURE_PROJECTS} \
    FEATURE_ABOUT=${FEATURE_ABOUT} \
    FEATURE_SEARCH=${FEATURE_SEARCH} \
    FEATURE_FLAG_BLOG=${FEATURE_FLAG_BLOG} \
    FEATURE_FLAG_PROJECTS=${FEATURE_FLAG_PROJECTS} \
    FEATURE_FLAG_ABOUT=${FEATURE_FLAG_ABOUT} \
    FEATURE_FLAG_SEARCH=${FEATURE_FLAG_SEARCH} \
    PUBLIC_FEATURE_FLAGS=${PUBLIC_FEATURE_FLAGS} \
    PUBLIC_FEATURE_BLOG=${PUBLIC_FEATURE_BLOG} \
    PUBLIC_FEATURE_PROJECTS=${PUBLIC_FEATURE_PROJECTS} \
    PUBLIC_FEATURE_ABOUT=${PUBLIC_FEATURE_ABOUT} \
    PUBLIC_FEATURE_SEARCH=${PUBLIC_FEATURE_SEARCH} \
    PUBLIC_FEATURE_FLAG_BLOG=${PUBLIC_FEATURE_FLAG_BLOG} \
    PUBLIC_FEATURE_FLAG_PROJECTS=${PUBLIC_FEATURE_FLAG_PROJECTS} \
    PUBLIC_FEATURE_FLAG_ABOUT=${PUBLIC_FEATURE_FLAG_ABOUT} \
    PUBLIC_FEATURE_FLAG_SEARCH=${PUBLIC_FEATURE_FLAG_SEARCH}

COPY . .
RUN bun run build

FROM nginx:stable-alpine AS runtime

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget -q -O /dev/null http://127.0.0.1/ || exit 1
